# Generated by Django 5.0.3 on 2024-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="source",
        ),
        migrations.AddField(
            model_name="customuser",
            name="area_code",
            field=models.CharField(blank=True, max_length=5, verbose_name="area_code"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=256, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("reviewer", "reviewer")],
                default="user",
                max_length=10,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="score",
            field=models.IntegerField(default=0, verbose_name="score"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, max_length=5, verbose_name="state"),
        ),
    ]
